name: devices_test
description: "A new Flutter project to list USB devices."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  usb_device: ^1.0.2
  cupertino_icons: ^1.0.8
  esc_pos_printer: ^4.1.0
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    