version: '3.8' 

services:
  mongo:
    image: mongo:latest 
    container_name: my-mongodb-container
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

volumes:
  mongo-data: 